//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Amb_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Tbl
    {
        public Category_Tbl()
        {
            this.Item_Tbl = new HashSet<Item_Tbl>();
        }
    
        public int categoryid { get; set; }
        public string categoryname { get; set; }
        public string categorydesc { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public int Item_Tbl_itemid { get; set; }
        public int Itemtype_TblItemTypeId { get; set; }
        public int Admin_Tbl_id { get; set; }
    
        public virtual ICollection<Item_Tbl> Item_Tbl { get; set; }
        public virtual Itemtype_Tbl Itemtype_Tbl { get; set; }
        public virtual Admin_Tbl Admin_Tbl { get; set; }
    }
}
