//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Amb_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Tbl
    {
        public int empid { get; set; }
        public string empname { get; set; }
        public string empusername { get; set; }
        public string emppassword { get; set; }
        public string empconfpassword { get; set; }
        public string empcontactno { get; set; }
        public string empmailid { get; set; }
        public string empaddress { get; set; }
        public Nullable<System.DateTime> dateofjoining { get; set; }
    }
}
