//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Amb_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itemtype_Tbl
    {
        public int ItemTypeId { get; set; }
        public string Type { get; set; }
        public string Createby { get; set; }
        public System.DateTime createddate { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> upadateddate { get; set; }
    }
}
