//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Amb_1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class Item_Tbl
    {
        public int itemid { get; set; }
        [Required, DisplayName("Item Name :")]
        public string iname { get; set; }
        [DisplayName("Description :")]
        [DataType(DataType.Html)]
        public string idesc { get; set; }
        [Required, DisplayName("Item Type:")]
        public string itype { get; set; }
        [AllowHtml]
        [DisplayName("Image :")]
        public byte[] iimage { get; set; }
        [Required, DisplayName("Price :")]
        public decimal iprice { get; set; }
        [Required, DisplayName("Category :")]
        public string icategory { get; set; }
        [Required, DisplayName("Created By :")]
        public string createdby { get; set; }
        [Required,DisplayName("Created Date :")]
        [DataType(DataType.Date)]
        public System.DateTime createddate { get; set; }
        [DisplayName("Updated By :")]
        public string updatedby { get; set; }
        [DisplayName("Updated Date:")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> updateddate { get; set; }
    }
}
