//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Amb_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Tbl
    {
        public int itemid { get; set; }
        public string iname { get; set; }
        public string idesc { get; set; }
        public string itype { get; set; }
        public byte[] iimage { get; set; }
        public decimal iprice { get; set; }
        public string icategory { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public int Category_Tbl_categoryid { get; set; }
        public int Itemtype_TblItemTypeId { get; set; }
        public int Admin_Tbl_id { get; set; }
        public int Admin_Tbl_id1 { get; set; }
    
        public virtual Category_Tbl Category_Tbl { get; set; }
        public virtual Itemtype_Tbl Itemtype_Tbl { get; set; }
        public virtual Admin_Tbl Admin_Tbl { get; set; }
    }
}
