//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Amb_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pickup_Tbl
    {
        public int storeid { get; set; }
        public string storelocation { get; set; }
        public string sotrecity { get; set; }
        public string storecontact1 { get; set; }
        public string storecontact2 { get; set; }
        public string storecontact3 { get; set; }
        public string createdby { get; set; }
        public System.DateTime createddate { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
    }
}
